version: '3'

services:
#  lavalink:
#    image: fredboat/lavalink:master
#    volumes:
#      - ./lavalink/application.yml:/opt/Lavalink/application.yml
  app:
    build: .
    depends_on:
      - discodo
  discodo:
    image: kijk2869/discodo:release-3.0.0
    volumes:
      - ./config.json:/opt/discodo/config.json
