version: '3'

services:
  lavalink:
    image: fredboat/lavalink:master
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
  app:
    build: .
    depends_on:
      - lavalink
